require('dotenv').config();

module.exports = [
    {
        name: 'default',
        type: 'postgres',
        url: process.env.DATABASE_URL,
        synchronize: false,
        logging: false,
        entities: ['./dist/entity/*.*'],
        migrations: ['./dist/database/migrations/**/*.js'],
        subscribers: ['./dist/database/subscribers/**/*.js'],
        cli: {
            entitiesDir: 'dist/entity',
            migrationsDir: 'dist/database/migrations',
            subscribersDir: 'dist/database/subscribers',
        },
    },
    {
        name: 'development',
        type: 'postgres',
        host: process.env.PG_HOST,
        port: process.env.PG_PORT,
        username: process.env.PG_USERNAME,
        password: process.env.PG_PASSWORD,
        database: process.env.PG_DATABASE,
        synchronize: true,
        logging: true,
        entities: ['src/entity/*.*'],
        migrations: ['src/database/migrations/**/*.ts'],
        subscribers: ['src/database/subscribers/**/*.ts'],
        cli: {
            entitiesDir: 'src/entity',
            migrationsDir: 'src/database/migrations',
            subscribersDir: 'src/database/subscribers',
        },
    },
    {
        name: 'test',
        type: 'postgres',
        host: process.env.PG_HOST,
        port: process.env.PG_PORT,
        username: process.env.PG_USERNAME,
        password: process.env.PG_PASSWORD,
        database: process.env.PG_TESTDATABASE,
        synchronize: false,
        logging: true,
        entities: ['src/entity/*.*'],
        migrations: ['src/database/migrations/**/*.ts'],
        subscribers: ['src/database/subscribers/**/*.ts'],
        cli: {
            entitiesDir: 'src/entity',
            migrationsDir: 'src/database/migrations',
            subscribersDir: 'src/database/subscribers',
        },
    },
    {
        name: 'production',
        type: 'postgres',
        url: process.env.DATABASE_URL,
        synchronize: false,
        logging: false,
        entities: ['dist/entity/*.*'],
        migrations: ['dist/database/migrations/**/*.js'],
        subscribers: ['dist/database/subscribers/**/*.js'],
        cli: {
            entitiesDir: 'dist/entity',
            migrationsDir: 'dist/database/migrations',
            subscribersDir: 'dist/database/subscribers',
        },
    },
    {
        name: 'github',
        type: 'postgres',
        host: process.env.POSTGRES_HOST,
        port: process.env.POSTGRES_PORT,
        username: process.env.POSTGRES_USER,
        password: process.env.POSTGRES_PASSWORD,
        database: process.env.POSTGRES_DB,
        synchronize: false,
        logging: false,
        entities: ['dist/entity/*.js'],
        migrations: ['dist/database/migrations/**/*.js'],
        subscribers: ['dist/database/subscribers/**/*.js'],
        cli: {
            entitiesDir: 'dist/entity',
            migrationsDir: 'dist/database/migrations',
            subscribersDir: 'dist/database/subscribers',
        },
        // runMigrations: true,
    },
    {
        name: 'githubtest',
        type: 'postgres',
        host: process.env.POSTGRES_HOST,
        port: process.env.POSTGRES_PORT,
        username: process.env.POSTGRES_USER,
        password: process.env.POSTGRES_PASSWORD,
        database: process.env.POSTGRES_DB,
        synchronize: false,
        logging: false,
        entities: ['src/entity/*.ts'],
        migrations: ['src/database/migrations/**/*.ts'],
        subscribers: ['src/database/subscribers/**/*.ts'],
        cli: {
            entitiesDir: 'src/entity',
            migrationsDir: 'src/database/migrations',
            subscribersDir: 'src/database/subscribers',
        },
        // runMigrations: true,
    },
];
