name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:11
                env:
                    POSTGRES_USER: postgresuser
                    POSTGRES_PASSWORD: postgrespassword
                    POSTGRES_DB: postgres
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        strategy:
            matrix:
                node-version: [13.9.0]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run migrate:github
              env:
                  POSTGRES_USER: postgresuser
                  POSTGRES_PASSWORD: postgrespassword
                  POSTGRES_DB: postgres
                  POSTGRES_HOST: localhost
                  POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
            - run: npm run test:github
              env:
                  POSTGRES_USER: postgresuser
                  POSTGRES_PASSWORD: postgrespassword
                  POSTGRES_DB: postgres
                  POSTGRES_HOST: localhost
                  POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
                  NODE_ENV: githubtest
