# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TestSCPWebserver

on:
    push:
        branches: [tmp]
    pull_request:
        branches: [tmp]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [13.9.0]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
            - name: Deploy to server
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: dist
                  remote: staging.development-preview.de
                  recursive: true
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
